import { ContactProfile } from '@/types/contact';

export const SAMPLE_PROFILES: ContactProfile[] = [
  {
    id: 'founder-alex',
    cardName: 'Alex Rivers (Tech Founder)',
    firstName: 'Alex',
    lastName: 'Rivers',
    prefix: '',
    title: 'Founder & CEO',
    company: 'HyperScale AI',
    department: 'Leadership',
    headline: 'Building the autonomous agent computing stack ⚡️',
    phone: '+1 (555) 349-8201',
    workPhone: '+1 (555) 902-1144',
    whatsapp: '+15553498201',
    email: 'alex@hyperscale.ai',
    workEmail: 'ceo@hyperscale.ai',
    website: 'https://hyperscale.ai',
    linkedin: 'alex-rivers-ai',
    twitter: 'alexrivers',
    instagram: 'alexrivers.build',
    github: 'alexrivers',
    calendly: 'https://calendly.com/alex-hyperscale/30min',
    telegram: 'alexrivers_tech',
    address: '500 Howard Street, Suite 400',
    city: 'San Francisco',
    state: 'CA',
    country: 'United States',
    postalCode: '94105',
    note: 'Met at TechCrunch Disrupt / AI Founders Summit. Reach out anytime for partnership or angel syndicates.',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    themeColor: '#6366f1',
    qrForeground: '#0f172a',
    qrBackground: '#ffffff',
    qrMode: 'vcard',
    qrCenterIcon: 'phone',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 7,
    updatedAt: Date.now(),
  },
  {
    id: 'executive-elena',
    cardName: 'Dr. Elena Rostova (VP Design)',
    firstName: 'Elena',
    lastName: 'Rostova',
    prefix: 'Dr.',
    title: 'VP of Product Design',
    company: 'Luminary Systems',
    department: 'Product & Design',
    headline: 'Designing spatial interfaces & enterprise-grade human experiences',
    phone: '+44 20 7946 0912',
    workPhone: '+44 20 7946 0888',
    whatsapp: '+442079460912',
    email: 'elena.rostova@luminary.design',
    website: 'https://elena-rostova.design',
    linkedin: 'elena-rostova-design',
    twitter: 'elenarostova',
    instagram: 'elena.designlab',
    github: 'elenarostova',
    calendly: 'https://calendly.com/elena-rostova',
    address: '10 Finsbury Square',
    city: 'London',
    country: 'United Kingdom',
    postalCode: 'EC2A 1AF',
    note: 'Speaker on Modern UX Systems. Connect regarding keynotes, advisory, and product strategy.',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80',
    themeColor: '#0ea5e9',
    qrForeground: '#0369a1',
    qrBackground: '#ffffff',
    qrMode: 'vcard',
    qrCenterIcon: 'phone',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 3,
    updatedAt: Date.now(),
  },
  {
    id: 'sales-marcus',
    cardName: 'Marcus Vance (Enterprise Growth)',
    firstName: 'Marcus',
    lastName: 'Vance',
    prefix: '',
    title: 'Head of Global Growth',
    company: 'Apex Cloud Infrastructure',
    department: 'Sales & Solutions',
    headline: 'Scaling enterprise cloud solutions across North America & EMEA',
    phone: '+1 (415) 880-9923',
    workPhone: '+1 (800) 555-0199',
    whatsapp: '+14158809923',
    email: 'marcus.v@apexcloud.io',
    workEmail: 'growth@apexcloud.io',
    website: 'https://apexcloud.io',
    linkedin: 'marcus-vance-cloud',
    twitter: 'marcusvance_io',
    calendly: 'https://calendly.com/marcus-vance/intro',
    city: 'Austin',
    state: 'TX',
    country: 'United States',
    note: 'Let’s discuss cloud optimization and enterprise infrastructure discounts.',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    themeColor: '#10b981',
    qrForeground: '#064e3b',
    qrBackground: '#ffffff',
    qrMode: 'landing',
    qrCenterIcon: 'phone',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 1,
    updatedAt: Date.now(),
  }
];

export const DEFAULT_NEW_PROFILE: ContactProfile = {
  id: '',
  cardName: 'My Contact Card',
  firstName: '',
  lastName: '',
  prefix: '',
  title: '',
  company: '',
  department: '',
  headline: '',
  phone: '',
  workPhone: '',
  whatsapp: '',
  email: '',
  workEmail: '',
  website: '',
  linkedin: '',
  twitter: '',
  instagram: '',
  github: '',
  youtube: '',
  calendly: '',
  telegram: '',
  address: '',
  city: '',
  state: '',
  country: '',
  postalCode: '',
  note: '',
  avatarUrl: '',
  themeColor: '#6366f1',
  qrForeground: '#0f172a',
  qrBackground: '#ffffff',
  qrMode: 'vcard',
  qrCenterIcon: 'phone',
  createdAt: Date.now(),
  updatedAt: Date.now(),
};
