import { ContactProfile } from '@/types/contact';

export const SAMPLE_PROFILES: ContactProfile[] = [
  {
    id: 'founder-alex',
    cardName: 'Alex Rivers (AI Agency Founder)',
    firstName: 'Alex',
    lastName: 'Rivers',
    prefix: '',
    title: 'Founder & AI Systems Lead',
    company: 'AI Founder Hub',
    department: 'AAA Accelerator',
    headline: 'Building & deploying autonomous AI lead management systems and voice agents ⚡️',
    phone: '+1 (555) 349-8201',
    workPhone: '+971 4 399 2200',
    whatsapp: '+15553498201',
    email: 'alex@aifounderhub.com',
    workEmail: 'founders@aifounderhub.com',
    website: 'https://aifounderhub.com',
    linkedin: 'alex-rivers-ai',
    twitter: 'alexrivers',
    instagram: 'alexrivers.build',
    github: 'alexrivers',
    calendly: 'https://calendly.com/alex-aifounderhub/intro',
    telegram: 'alex_aifounderhub',
    address: 'Dubai Internet City, Building 3',
    city: 'Dubai',
    state: 'Dubai',
    country: 'United Arab Emirates',
    postalCode: '00000',
    note: 'Member of AI Founder Hub (aifounderhub.com). Connect regarding AI Agency Accelerator, live build nights, and client acquisition.',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    themeColor: '#ccf244',
    qrForeground: '#07070b',
    qrBackground: '#ffffff',
    qrMode: 'vcard',
    qrCenterIcon: 'phone',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 7,
    updatedAt: Date.now(),
  },
  {
    id: 'mentor-ahmed',
    cardName: 'Ahmed Al Kindi (Growth & Systems)',
    firstName: 'Ahmed',
    lastName: 'Al Kindi',
    prefix: '',
    title: 'Cofounder, Growth & Systems',
    company: 'AI Founder Hub',
    department: 'Accelerator Mentorship',
    headline: 'Scaling AI automation agencies to $10K+/month. Dubai & Global.',
    phone: '+971 50 123 4567',
    workPhone: '+971 4 399 2200',
    whatsapp: '+971501234567',
    email: 'ahmed@aifounderhub.com',
    website: 'https://aifounderhub.com',
    linkedin: 'ahmed-alkindi-growth',
    twitter: 'ahmedalkindi',
    calendly: 'https://calendly.com/ahmed-alkindi/accelerator',
    city: 'Dubai',
    country: 'United Arab Emirates',
    note: 'Mentor at AI Founder Hub. Reach out for 1:1 founder checkpoints and agency scaling.',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    themeColor: '#ccf244',
    qrForeground: '#07070b',
    qrBackground: '#ffffff',
    qrMode: 'landing',
    qrCenterIcon: 'phone',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 3,
    updatedAt: Date.now(),
  },
  {
    id: 'designer-elena',
    cardName: 'Dr. Elena Rostova (Product & AI UX)',
    firstName: 'Elena',
    lastName: 'Rostova',
    prefix: 'Dr.',
    title: 'Lead AI Product Designer',
    company: 'Luminary AI Systems',
    department: 'Product Lab',
    headline: 'Designing high-converting conversational agents and human-AI interfaces',
    phone: '+44 20 7946 0912',
    workPhone: '+44 20 7946 0888',
    whatsapp: '+442079460912',
    email: 'elena.rostova@luminary.design',
    website: 'https://elena-rostova.design',
    linkedin: 'elena-rostova-design',
    twitter: 'elenarostova',
    instagram: 'elena.designlab',
    github: 'elenarostova',
    calendly: 'https://calendly.com/elena-rostova',
    city: 'London',
    country: 'United Kingdom',
    note: 'Speaker at AI Founder Hub Masterclasses. Connect regarding AI UI/UX audits and product design.',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80',
    themeColor: '#b5a1ff',
    qrForeground: '#07070b',
    qrBackground: '#ffffff',
    qrMode: 'vcard',
    qrCenterIcon: 'phone',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 1,
    updatedAt: Date.now(),
  }
];

export const DEFAULT_NEW_PROFILE: ContactProfile = {
  id: '',
  cardName: 'My AI Founder Card',
  firstName: '',
  lastName: '',
  prefix: '',
  title: '',
  company: '',
  department: '',
  headline: '',
  phone: '',
  workPhone: '',
  whatsapp: '',
  email: '',
  workEmail: '',
  website: '',
  linkedin: '',
  twitter: '',
  instagram: '',
  github: '',
  youtube: '',
  calendly: '',
  telegram: '',
  address: '',
  city: '',
  state: '',
  country: '',
  postalCode: '',
  note: '',
  avatarUrl: '',
  themeColor: '#ccf244',
  qrForeground: '#07070b',
  qrBackground: '#ffffff',
  qrMode: 'vcard',
  qrCenterIcon: 'phone',
  createdAt: Date.now(),
  updatedAt: Date.now(),
};
